  # This workflow will install Python dependencies, run tests and lint with a single version of Python
  # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

  name: Python application

  on:
    push:
      tags:
        - 'v*'

  jobs:
    make_release:
      runs-on: ubuntu-latest
      outputs:
        upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
      steps:
        - name: Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: false

        - id: step_upload_url
          run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

        - name: Add file to release
          uses: actions/upload-artifact@v2
          with:
            name: user_guide
            path: user_guide.pdf

        - name: Get release ID
          id: get_release
          uses: actions/github-script@v4
          with:
            script: |
              const release = await github.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: context.ref
              });
              console.log(release.data.id);

        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: user_guide
            path: user_guide.pdf

        - name: Add file to release assets
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: user_guide.pdf
            asset_name: user_guide.pdf
            asset_content_type: application/pdf

    build_windows:
      runs-on: windows-latest
      needs: make_release
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python -m pip install pyinstaller
        - name: Build
          run: |
            pyinstaller marel_marine_scale_controller.spec
            powershell Compress-Archive .\dist\MarelApp\ -DestinationPath MarelApp.zip
        - name: Upload release asset
          id: upload-release-asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.make_release.outputs.upload_url }}
            asset_path: .\MarelApp.zip
            asset_name: MarelApp-windows.zip
            asset_content_type: application/octet-stream


    build_linux:
      runs-on: ubuntu-latest
      needs: make_release
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
      - name: Build
        run: |
          pyinstaller marel_marine_scale_controller.spec
          zip -r MarelApp.zip ./dist/MarelApp/
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.make_release.outputs.upload_url }}
          asset_path: ./MarelApp.zip
          asset_name: MarelApp-linux.zip
          asset_content_type: application/octet-stream


